// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: category.sql

package db

import (
	"context"
	"database/sql"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO "categories" ("name",
                          "key")
VALUES ($1, $2)
RETURNING key, name, created_at
`

type CreateCategoryParams struct {
	Name string `json:"name"`
	Key  string `json:"key"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.Key)
	var i Category
	err := row.Scan(&i.Key, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE
FROM "categories"
WHERE "key" = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, key string) error {
	result, err := q.db.ExecContext(ctx, deleteCategory, key)
	if err != nil {
		return err
	}
	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if rowsAffected == 0 {
		return sql.ErrNoRows
	}
	return nil
}

const getCategory = `-- name: GetCategory :one
SELECT key, name, created_at
FROM "categories"
WHERE "key" = $1
LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, key string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, key)
	var i Category
	err := row.Scan(&i.Key, &i.Name, &i.CreatedAt)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT key, name, created_at
FROM "categories"
ORDER BY "created_at"
LIMIT $1 OFFSET $2
`

type ListCategoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.Key, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE "categories"
SET "name" = $2
WHERE "key" = $1
RETURNING key, name, created_at
`

type UpdateCategoryParams struct {
	Key  string `json:"key"`
	Name string `json:"name"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory, arg.Key, arg.Name)
	var i Category
	err := row.Scan(&i.Key, &i.Name, &i.CreatedAt)
	return i, err
}

const listCategoryQuestions = `-- name: listCategoryQuestions :many
SELECT id, text, hint, category, created_at
FROM questions
WHERE category = $1
ORDER BY "created_at"
LIMIT $2 OFFSET $3
`

type ListCategoryQuestionsParams struct {
	Category string `json:"category"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListCategoryQuestions(ctx context.Context, arg ListCategoryQuestionsParams) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listCategoryQuestions, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Hint,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
