// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"
)

type Answer struct {
	ID         int64  `json:"id"`
	QuestionID int64  `json:"question_id"`
	Text       string `json:"text"`
	IsCorrect  bool   `json:"is_correct"`
}

type AnsweredQuestion struct {
	UserID     int64     `json:"user_id"`
	QuestionID int64     `json:"question_id"`
	AnsweredAt time.Time `json:"answered_at"`
}

type Category struct {
	// name for user
	Name string `json:"name"`
	// name for dev
	Key string `json:"key"`
}

type Question struct {
	ID       int64  `json:"id"`
	Text     string `json:"text"`
	Hint     string `json:"hint"`
	Category string `json:"category"`
}

type User struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
