// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"
)

type Answer struct {
	ID         int64     `json:"id"`
	QuestionID int64     `json:"question_id"`
	Text       string    `json:"text"`
	IsCorrect  bool      `json:"is_correct"`
	CreatedAt  time.Time `json:"created_at"`
}

type AnsweredQuestion struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	QuestionID int64     `json:"question_id"`
	AnsweredAt time.Time `json:"answered_at"`
}

type Category struct {
	ID int64 `json:"id"`
	// name for dev
	Key string `json:"key"`
	// name for user
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Question struct {
	ID        int64     `json:"id"`
	Text      string    `json:"text"`
	Hint      string    `json:"hint"`
	Category  string    `json:"category"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID             int64     `json:"id"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
}
