// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "users" ("email",
                     "password")
VALUES ($1, $2)
RETURNING id, email, password, created_at
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE
FROM "users"
WHERE "id" = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password, created_at
FROM "users"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUserAnsweredQuestionsCount = `-- name: GetUserAnsweredQuestionsCount :one
SELECT COUNT(*)
FROM "answered_questions" AS aq
         JOIN "questions" AS q ON aq.question_id = q.id
WHERE aq.user_id = $1
  AND ($2::TEXT = '' OR q.category = $2::TEXT)
`

type GetUserAnsweredQuestionsCountParams struct {
	UserID   int64  `json:"user_id"`
	Category string `json:"category"`
}

func (q *Queries) GetUserAnsweredQuestionsCount(ctx context.Context, arg GetUserAnsweredQuestionsCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserAnsweredQuestionsCount, arg.UserID, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUsersCount = `-- name: GetUsersCount :one
SELECT COUNT(*)
FROM "users"
`

func (q *Queries) GetUsersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUsersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUserAnsweredQuestions = `-- name: ListUserAnsweredQuestions :many
SELECT q.id, q.text, q.hint, q.category, q.created_at
FROM "answered_questions" AS aq
         JOIN "questions" AS q ON aq.question_id = q.id
WHERE aq.user_id = $3
  AND ($4::TEXT = '' OR q.category = $4::TEXT)
LIMIT $1 OFFSET $2
`

type ListUserAnsweredQuestionsParams struct {
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
	UserID   int64  `json:"user_id"`
	Category string `json:"category"`
}

func (q *Queries) ListUserAnsweredQuestions(ctx context.Context, arg ListUserAnsweredQuestionsParams) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listUserAnsweredQuestions,
		arg.Limit,
		arg.Offset,
		arg.UserID,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Hint,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password, created_at
FROM "users"
ORDER BY "id"
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE "users"
SET "password" = $2
WHERE "id" = $1
RETURNING id, email, password, created_at
`

type UpdateUserParams struct {
	ID       int64  `json:"id"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.ID, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
